server:
  port: 7001

eureka:
  instance:
    hostname: discover
    prefer-ip-address: false
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心
    service-url:
      defaultZone: http://discover:7001/eureka/
      #http://${eureka.instance.hostname}:${server.port}/eureka/ #设置和Eureka server交互的地址查询服务和注册需要依赖这个地址
