spring:

  application:
    name: webShop-buyCar

  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/webShop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root

server:
  port: 8002

mybatis:
  mapper-locations: classpath:mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: webShop-buyCar:8002
    prefer-ip-address: true

logging:
  level:
    com.project.webshop.buycar.mapper.BuyCarMapper: debug

info:
  app.name: test-cloud
  company.name: wwww.testCloud.com
  build.artifactId: $project.artifactId$
  builid.version: $project.version$
